# Generated by Django 4.2.2 on 2024-06-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='entity',
            name='time',
            field=models.CharField(max_length=255),
        ),
    ]
